"""Add state and rusa_phase foreign keys

Revision ID: 00fc29219689
Revises: e71b0198f951
Create Date: 2025-11-27 05:29:16.069448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fc29219689'
down_revision = 'e71b0198f951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rusa_phase_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mpr_report_rusa_phase_id', 'rusa_phases', ['rusa_phase_id'], ['id'])
        batch_op.create_foreign_key('fk_mpr_report_state_id', 'states', ['state_id'], ['id'])
        batch_op.drop_column('physical_inspection_reports_pir_')
        batch_op.drop_column('number_of_students_benefitted')
        batch_op.drop_column('pir_uploaded_yes_no_not_selected_')
        batch_op.drop_column('benfits_from_the_projects_please_provide_details_')
        batch_op.drop_column('number_of_research_works_being_undertaken')
        batch_op.drop_column('number_of_faculties_benefitted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_faculties_benefitted', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('number_of_research_works_being_undertaken', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('benfits_from_the_projects_please_provide_details_', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pir_uploaded_yes_no_not_selected_', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('number_of_students_benefitted', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('physical_inspection_reports_pir_', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_mpr_report_state_id', type_='foreignkey')
        batch_op.drop_constraint('fk_mpr_report_rusa_phase_id', type_='foreignkey')
        batch_op.drop_column('rusa_phase_id')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###
