"""Add Component table and many-to-many relationship with RusaPhase

Revision ID: 57038ca027ec
Revises: 6d44c880d062
Create Date: 2025-11-27 06:00:26.741615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57038ca027ec'
down_revision = '6d44c880d062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rusa_phase_components',
    sa.Column('rusa_phase_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['rusa_phase_id'], ['rusa_phases.id'], ),
    sa.PrimaryKeyConstraint('rusa_phase_id', 'component_id')
    )
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mpr_report_component_id', 'components', ['component_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mpr_report_component_id', type_='foreignkey')
        batch_op.drop_column('component_id')

    op.drop_table('rusa_phase_components')
    op.drop_table('components')
    # ### end Alembic commands ###
