"""Remove component_name from MprReport

Revision ID: 64952bf22637
Revises: cf560ec062d4
Create Date: 2025-11-27 06:10:27.643292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64952bf22637'
down_revision = 'cf560ec062d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.drop_column('component_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_name', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
