"""Restore deleted columns

Revision ID: 6d44c880d062
Revises: 00fc29219689
Create Date: 2025-11-27 05:46:07.496340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d44c880d062'
down_revision = '00fc29219689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benfits_from_the_projects_please_provide_details_', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('number_of_students_benefitted', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('number_of_faculties_benefitted', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('number_of_research_works_being_undertaken', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('physical_inspection_reports_pir_', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pir_uploaded_yes_no_not_selected_', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.drop_column('pir_uploaded_yes_no_not_selected_')
        batch_op.drop_column('physical_inspection_reports_pir_')
        batch_op.drop_column('number_of_research_works_being_undertaken')
        batch_op.drop_column('number_of_faculties_benefitted')
        batch_op.drop_column('number_of_students_benefitted')
        batch_op.drop_column('benfits_from_the_projects_please_provide_details_')

    # ### end Alembic commands ###
