"""Normalize components

Revision ID: cf560ec062d4
Revises: 57038ca027ec
Create Date: 2025-11-27 06:03:41.157570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf560ec062d4'
down_revision = '57038ca027ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mpr_report_component_id', 'components', ['component_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpr_report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mpr_report_component_id', type_='foreignkey')
        batch_op.drop_column('component_id')

    # ### end Alembic commands ###
